version: '3.7'
services:
    nginx:
        image: nginx:latest
        network_mode: bridge
        container_name: nginx
        hostname: nginx.container
        restart: always
        ports:
            - 80:80
        volumes:
            - ./conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log/nginx
            - ./html:/usr/share/nginx/html
